# -*- coding: utf-8 -*-
"""4 thoughts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YMc0oIuRxc6mjVznznnLeigdGbkHsTaz
"""

operations = {"+","-","*","//"}
num = int(input())
for i in range(num):
  val = int(input())
  if val <-60 or val >256:
    print("no solution")
  else:
    for x in operations:
      for y in operations:
        for z in operations:
          expression = "4{:s}4{:s}4{:s}4".format(x,y,z)
          actual_val = eval(expression)
          found  = False
          if int(actual_val) == val:
            found = True
            break
        if found:
          break
      if found:
        break
          
    
    if found:
      expression = expression.replace("//","/")
      print(" ".join(expression),"=",val)
    else:
      print("no solution")

eval("4-4/4+4")

