# -*- coding: utf-8 -*-
"""a_different_prob.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r9Iaq5iybCwAI7Xa5PndiUmcJ-6r5xbt
"""

try:
  while (True):
    a,b = map(int,input().split())
    print(abs(a-b))
except EOFError:
  pass

import sys

for i in sys.stdin:
    a, b = [int(x) for x in i.split()]
    print(abs(a - b))