# -*- coding: utf-8 -*-
"""aaah.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1akT86jU8zPjkhYGQlxm5TAixte9BrebU
"""

from sys import stdin
a = len(stdin.readline())
b = len(stdin.readline())
if a >= b:
  print('go')
else:
  print('no')