# -*- coding: utf-8 -*-
"""Akcija.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X1CMFX_UDhgEcO3d3YT4MqBlJJC6tWrO
"""

num = int(input())
sum = 0
val = []
for i in range(num):
  val.append(int(input()))
val = sorted(val,reverse = True)
j = 1
sum = 0
for v in val:
  if j%3 !=0:
    sum += v
  j += 1
print(sum)

from sys import stdin,stdout
num =stdin.read()
print(num)
sum = 0
val = []
# for i in range(int(num)):
#   val.append(int(input()))
# val = sorted(val,reverse = True)
# j = 1
# sum = 0
# for v in val:
#   if j%3 !=0:
#     sum += v
#   j += 1
# print(sum)

! python code.py <input.txt

