# -*- coding: utf-8 -*-
"""Alphabet_spam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZH7A81k5Gx8U5Xw9l5XgHT98qjh9AjL4
"""

input_ = input()
whitespace = 0
lowercase = 0
uppercase = 0
symbols = 0
for letters in input_:
  if letters =='_':
    whitespace += 1
  elif letters.islower():
    lowercase += 1
  elif letters.isupper():
    uppercase += 1
  else:
    symbols += 1
total_length = len(input_)
print(whitespace/total_length)
print(lowercase/total_length)
print(uppercase/total_length)
print(symbols/total_length)

