# -*- coding: utf-8 -*-
"""Apaxian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KM0_7waHM6MKMaU_VsNgQCuQgABQxkJs
"""

y,p = input().split()
vowel = ['a','e','i','o','u']

if y[-1] in vowel:
  y =y[:-1]
  print(y+"ex"+p)
elif y.endswith("ex"):
  print(y+p)
else:
  print(y+"ex"+p)

