# -*- coding: utf-8 -*-
"""area_circle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZlazged5PmDpuGS6vqWXPEXOhZIgtZl
"""

import math
def inputs ():
  values = []
  itr = 0
  while (itr !=1):
    val = list(map(float,input().split()))
    if val[0] == 0 and val[1] ==0 and val[2] == 0:
      itr = 1
    else:
      values.append(val)
  return values
  
def print_val(data):
  for i in range(len(data)):
    area_square = (data[i][0]*2)**2
    est_dots = data[i][2]/data[i][1]
    est_area = est_dots * area_square
    print(math.pi*(data[i][0]**2)," ",est_area)

data = inputs()

print_val(data)

