# -*- coding: utf-8 -*-
"""Baby Bites.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qfPzXH88I9e8dmvfrDiAW8Fzx-n38KLR
"""

num = int(input())
values = input().split()
Fishy = False
for i in range(num):
  if values[i].isdigit():
    if int(values[i]) != i+1:
      Fishy = True
      break
if Fishy:
  print("something is fishy")
else:
  print("makes sense")