# -*- coding: utf-8 -*-
"""Batter_up

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSeglQ_tmlhmyHlXk6vDFU5YLhdI3ii3
"""

num = int(input())
list_ = list(map(int,input().split()))
count = 0
total = 0
for points in list_:
  if points >=0:
    total += points
    count += 1
print(total/count)

