# -*- coding: utf-8 -*-
"""Bijelie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lfsji_pz6r2CED-iWAv54e51KHfXviFi
"""

a,b,c,d,e,f=map(int,input().split())
print(1-a,1-b,2-c,2-d,2-e,8-f)