# -*- coding: utf-8 -*-
"""Boat_parts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FQ1uYxPfSngHvgakV2ll42fGkhlpw-E
"""

p,n = map(int,input().split())
parts = []
ans = []
Found = False
for i in range(n):
  bought = input()
  if bought not in parts:
    parts.append(bought)
  if len(parts) == p:
    Found = True
    ans.append(i+1)
if Found:
  print(ans[0])
else:
  print("paradox avoided")

