# -*- coding: utf-8 -*-
"""Ceitri.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zfUcwKVLNl8Aw0LdKvn0ata76ew2Libd
"""

l = list(map(int,input().split()))
l = sorted(l)
a,b,c = l[0],l[1],l[2]
x = b - a
y = c - b
if (x ==y):
  print(c+y)
elif x < y:
    print(b + x)
else:
    print(a + y)