# -*- coding: utf-8 -*-
"""Das_blinkenlights.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ykCQ8uyDbUJBqw6QWsBC43HrNUoX9RZB
"""

p,q,s = map(int,input().split())
array_p = []
array_q = []
ans =[]
for i in range(1,s+1):
  p_val = p*i
  q_val = q*i
  if (p_val<=s):
    array_p.append(p_val)
  if (q_val <=s):
    array_q.append(q_val)
for k in array_p:
  if k in array_q:
    ans.append("yes")
  else:
    ans.append("no")
if "yes" in ans:
  print("yes")
else:
  print("no")