# -*- coding: utf-8 -*-
"""Datum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SXN7b06yebOXz4r5wAV26_F-A7npsDbM
"""

a,b = map(int,input().split())
mnths = [31,28,31,30,31,30,31,31,30,31,30,31]
days = ["Wednesday","Thursday","Friday","Saturday","Sunday","Monday","Tuesday"]
for i in range(0,b-1):
  a += mnths[i]
print(days[(a%7)])