# -*- coding: utf-8 -*-
"""Death knight Hero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mLoPPqvbvIcBSH1hlOrSihInpWXewqQS
"""

num = int(input())
title = 0
for k in range(num):
  words = input()
  if "CD" not in words:
    title += 1
print(title)

