# -*- coding: utf-8 -*-
"""dice_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wcQPXYgT34O5GQcAzlVWIIJMrZzJkKdL
"""

from sys import stdin
list_1 = list(map(int,input().split()))
list_2 = list(map(int,input().split()))
a = sum(list_1)
b = sum(list_2)
if a>b:
  print("Gunnar")
elif a<b:
  print("Emma")
else:
  print("tie")