# -*- coding: utf-8 -*-
"""different_distances.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12BX37q2MbZtXUuy8NIoolX7nOy64Na4N
"""

itr = 0
data = []
while(itr !=1):
  values = list(map(float,input().split()))
  if 0 in values:
    itr = 1
  else:
    data.append(values)

for i in range(len(data)):
  distance = (abs((data[i][0] - data[i][2])**data[i][4])+abs((data[i][1]-data[i][3]))**data[i][4])**(1/data[i][4])
  print(round(distance,10))

