# -*- coding: utf-8 -*-
"""Egypt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17q9x97wjZtHvAEBW2dkL7QPbuXeW7eZ8
"""

while(True):
  l = list(map(int,input().split()))
  l = sorted(l)
  a,b,c = l[0],l[1],l[2]
  if a == 0 and b == 0 and c == 0:
    break
  if c**2 == a **2 + b **2:
    print("right")
  else:
    print("wrong")

from sys import stdin,stdout
while(True):
 l =  list(map(int,stdin.readline().split()))
 l = sorted(l)
 a,b,c = l[0],l[1],l[2]
 if a == 0 and b == 0 and c == 0:
   break
 if c**2 == a **2 + b **2:
  stdout.write("right\n")
 else:
  stdout.write("wrong\n")