# -*- coding: utf-8 -*-
"""Eligibility.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDnvuSLRH2N2RifGdIGyjsmFZd6-MUNo
"""

num = int(input())
for _ in range(num):
  name, post_secondary, D0B,courses = input().split()
  ps = post_secondary[0]+ post_secondary[1]+post_secondary[2]+post_secondary[3]
  Db = D0B[0]+D0B[1]+D0B[2]+D0B[3]
  if int(ps) >=2010 or int(Db)>=1991:
    print(name,"eligible")
  elif int(courses) >=41:
    print(name,"ineligible")
  else:
    print(name,"coach petitions")

from sys import stdin

num = int(stdin.readline())
for _ in range(num):
  name, post_secondary, D0B,courses = stdin.readline().split()
  ps = post_secondary[0]+ post_secondary[1]+post_secondary[2]+post_secondary[3]
  Db = D0B[0]+D0B[1]+D0B[2]+D0B[3]
  if int(ps) >=2010 or int(Db)>=1991:
    print(name,"eligible")
  elif int(courses) >=41:
    print(name,"ineligible")
  else:
    print(name,"coach petitions")

! python eligibility.py < input.txt

