# -*- coding: utf-8 -*-
"""Engineering_English.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ae5px228TgQHUFX0Yu87Hlah7BYs7Szf
"""

sentence = []
while (True):
  try:
    words = input().split()
    if len(words) ==0:
      break
    for word in words:
      if word.lower() in sentence:
        print(".",end = ' ')
      else:
        sentence.append(word.lower())
        print(word,end = ' ') 
  except EOFError:
    break