# -*- coding: utf-8 -*-
"""Exam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/194DKK6EuBmNJk3T3-IC2vX-xISiOQULX
"""

num = int(input())
mine = list(input())
friends = list(input())
fw= len(mine) - num
match = 0
for i in range(len(mine)):
  if mine[i] == friends[i]:
    match += 1
unmatch = len(mine) - match
if num == len(mine):
  print(match)
else:
  print(unmatch + match - abs(match - num))

