# -*- coding: utf-8 -*-
"""Dice_Cup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10JDlhxxw7yJ9TirGEsM4KkYDdfk8daYs
"""

a,b = map(int,input().split())
if a==b:
  print(a+1)
else:
  for i in range(min(a,b)+1,max(a,b)+2):
    print(i)