# -*- coding: utf-8 -*-
"""fifty_shades_of_pink.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uYVnNzGIQt6FF-XBX633FHktZVOoxawZ
"""

num = int(input())
count = 0
for i in range(num):
  name=input()
  if "rose" in name.lower() or "pink" in name.lower():
    count +=1
if count !=0:
  print(count)
else:
  print("I must watch Star Wars with my daughter")