# -*- coding: utf-8 -*-
"""Forced_choice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bn-VqD2vI0qbLOqCh2uxqXcisWvhB6dt
"""

_,c,n = map(int,input().split())
for i in range(n):
  list_ = list(map(int,input().split()))
  if c in list_[1:]:
    print("keep")
  else:
    print("remove")

10 3 4
2 1 5
5 2 3 7 8 10
3 2 7 10
1 8