# -*- coding: utf-8 -*-
"""Free_food.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HVd1zENL01YAHtjHs4oY99MrIcUsS-mg
"""

values = []
for _ in range(int(input())):
  a,b = map(int,input().split())
  for k in range(a,b+1):
    values.append(k)
print(len(set(values)))