# -*- coding: utf-8 -*-
"""FYI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AYV1QZDiW8Lq9XEh5wmoCNZL_fxu8xyj
"""

import sys
num = sys.stdin.readline()
num_list = list (num)
prfix = num_list[0]+num_list[1]+num_list[2]
if prfix == "555":
  print(1)
else:
  print(0)