# -*- coding: utf-8 -*-
"""Hangman.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NsDey9wulhJSR42KpuWsDdlGNzBkj8Hf
"""

words = list (input())
permutation = input()
count = 0
found = len(set(words))
kill = False
while (not kill):
  for letter in permutation:
    if letter in words:
      found -= 1
    else:
      count += 1
    if found == 0 or count ==10:
      kill = True
      break
    
if found ==0:
  print("WIN")
else:
  print("LOSE")