# -*- coding: utf-8 -*-
"""Homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1080P6LyLlaQnWpq1ExmgMe2zj5LYZVc9
"""

values = input()
init = values.count(";")
arrays = values.split(";")
for value in arrays:
  if "-" in value:
    a,b = value.split("-")
    for i in range(int(a),int(b)):
      init +=1
print(init+1)