# -*- coding: utf-8 -*-
"""Kemija.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S8fMiP3V3EBBKjM9WwjajBr7AISjbth5
"""

def ans():
  inputs_ = input()
  inputs_ = inputs_.replace("apa","a")
  inputs_ = inputs_.replace("epe","e")
  inputs_ = inputs_.replace("ipi","i")
  inputs_ = inputs_.replace("opo","o")
  inputs_ =inputs_.replace("upu","u")
  return inputs_
print(ans())

