# -*- coding: utf-8 -*-
"""Left_Beehind.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Spevdkec7FEWiYLny8v9NbxzYGWHmQhI
"""

while(True):
  sweet,sour  = map(int,input().split())
  if sweet == 0 and sour == 0 :
    break
  if sweet + sour == 13:
    print("Never speak again.")
  elif sweet < sour:
    print("Left beehind.")
  elif sweet > sour:
    print("To the convention.")
  else:
    print("Undecided.")