# -*- coding: utf-8 -*-
"""Line_them.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGaAIYkNjYX-d2e2H4_U-v0XWpfQ_iEA
"""

num = int(input())
name_array = []
for i in range(num):
  name = input()
  name_array.append(name)
ans = all(i < j for i, j in zip(name_array, name_array[1:]))
if (ans):
  print("INCREASING")
else:
  if all(i > j for i, j in zip(name_array, name_array[1:])):
    print("DECREASING")
  else:
    print("NEITHER")