# -*- coding: utf-8 -*-
"""lost lineup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XH1iVdMlsJSBGOhar4edWI11ey7Mp3Ew
"""

num = int(input())
lst = [0]*num
lst[0] = 1
line = list(map(int,input().split()))
itr = 0
for i in range(2,num+1):
  lst[line[itr]+1] = i
  itr +=1
for k in lst:
  print(k,end = " ")