# -*- coding: utf-8 -*-
"""mirror images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aerJU6eF7OkEDsYK9NvIIt5Ap4Rtmnqs
"""

test = int(input())
for i in range(test):
  r,c = input().split()
  r = int(r)
  c = int(c)
  values = []
  for j in range(r):
    temp = input()
    values.append(temp)
  print("Test",i+1)
  idx = r-1
  for k in range(r):
    print(values[idx][::-1])
    idx -= 1