# -*- coding: utf-8 -*-
"""missing_number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uRQ-0oxXXvuJtLbXC1AhednS4CDh5X1c
"""

def input_vals():
  num = int(input())
  val = [int(input()) for i in range(0,num)]
  return val

def print_ans(data):
  for i in range(1,max(data)):
    if i not in data:
      print(i)
  if len(data) == max(data):
    print("good job")

print_ans(input_vals())

