# -*- coding: utf-8 -*-
"""Mixed_fractions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WZajUg-_-v-TOTDKNml3cKeanzFe7uXp
"""

while(True):
  a,b = map(int,input().split())
  if a==0 and b==0:
    break
  whole = int(a/b)
  frac = a%b
  print(whole,frac,"/",b)

from sys import stdin,stdout
while(True):
  a,b = map(int,stdin.readline().split())
  if a==0 and b ==0:
    break
  whole = int(a/b)
  frac = a%b
  stdout.write(str(whole)+ " "+ str(frac)+" / "+str(b)+"\n")

