# -*- coding: utf-8 -*-
"""mjehiric.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3webA0PFx-efKt06rW-mM2qYKEqM-1F
"""

list_ = list(input().split())
list_sort = sorted(list_)
while list_ != list_sort:
  for i in range(len(list_)):
    if i <len(list_)-1:
      if list_[i]>list_[i+1]:
        temp = list_[i+1]
        list_[i+1] = list_[i]
        list_[i] = temp
        for j in range(len(list_)):
          print(list_[j],end=" ")
        print()