# -*- coding: utf-8 -*-
"""odd Echo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQvEY67okC4YlmKpa01sJFkri2UiXZbr
"""

num = int(input())
for i in range(1,num+1):
  val = input()
  if i%2 == 1:
    print(val)

5
hello
i
am
an
echo