# -*- coding: utf-8 -*-
"""One_person_per_chicken.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/114KaKoJ8Syg-nYRVFFb76qGnt5cGqA2d
"""

a,b = map(int,input().split())
if a > b:
  k = a-b
  if k==1:
    print("Dr. Chaz needs",k,"more piece of chicken!")
  else:
    print("Dr. Chaz needs",k,"more pieces of chicken!")

else:
  k = b-a
  if k == 1:
    print("Dr. Chaz will have",k ,"piece of chicken left over!")
  else:
    print("Dr. Chaz will have", b-a ,"pieces of chicken left over!")