# -*- coding: utf-8 -*-
"""Poker Hand.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XDxoVTGLINam27uUIo6xgScsAHM2pHyl
"""

l = list(input().split())
dic = {}
for val in l:
  if val[0] in dic:
    dic[val[0]] +=1
  else:
    dic[val[0]] = 1
dic = sorted(dic.items(), key=lambda x: x[1], reverse=True)
print(dic[0][1])

