# -*- coding: utf-8 -*-
"""ptice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17FczE-GKmT2tPIXAA7GkZUOKb_PMt8gv
"""

num = int(input())
adrian =  [ 'A', 'B', 'C']
bruno  = ['B','A','B','C']
Goran = ['C','C','A','A','B','B']
letters = list(input())
right_ans = {}
count_ad = 0
count_bruno = 0
count_goran = 0
for i in range(len(letters)):
  idx_ad = i%3
  if (letters[i] == adrian[idx_ad]):
    count_ad += 1
    right_ans["Adrian"] = count_ad
  idx_br = i % 4

  if (letters[i] == bruno[idx_br]):
    count_bruno += 1
    right_ans["Bruno"] = count_bruno

  idx_go = i%6

  if (letters[i] == Goran[idx_go]):
    count_goran += 1
    right_ans["Goran"] = count_goran
max_count = max(count_ad,count_bruno,count_goran)
print(max_count)
if (max_count == count_ad):
  print("Adrian")
if (max_count == count_bruno):
  print("Bruno")
if (max_count == count_goran):
  print("Goran")

Adrian
Bruno
Goran



