# -*- coding: utf-8 -*-
"""quality_life.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15wszUJgj-uwUTISFLFroGe2HHR3IKELV
"""

sum = 0
num = int(input())
for i in range(num):
  a,b = map(float,input().split())
  sum += a*b
print(sum)