# -*- coding: utf-8 -*-
"""Quick_brown.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HkwjALTE5l08XpMHIctqpWTx2dSqiN4-
"""

num = int(input())
for i in range(num):
  alphabet = "abcdefghijklmnopqrstuvwxyz"
  sentence = input()
  sentence = sentence.lower()
  missing = ''
  for letter in alphabet:
    if letter not in sentence:
      missing = missing+letter
  if (len(missing) != 0):
    print("missing", missing)
  else:
    print("pangram")