# -*- coding: utf-8 -*-
"""Racing _Around_Alphabet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B4UZBJiJdAnN5UVyTJnsVsNXeVWFaVX1
"""

import math
num = int(input())
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ '"

for i in range(num):
  sentence = input()
  default_dist = len(sentence)
  distance = 0
  current_position = alphabet.index(sentence[0])
  for j in range(1,len(sentence)):
    next_letter = alphabet.index(sentence[j])
    distance += min(abs(current_position-next_letter),28 - abs(current_position-next_letter))
    current_position = next_letter
  total_distance = default_dist + (distance*math.pi)/7
  print(total_distance)