# -*- coding: utf-8 -*-
"""RatingProblem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Engua8LTlL8SCov7vD6ldPfwF7in7o-f
"""

judge,rated = map(int,input().split())
add = (judge - rated)*3
sum = 0.0
for i in range(rated):
  val = int(input())
  sum += val
print((sum-add)/judge, (sum+add)/judge)



2