# -*- coding: utf-8 -*-
"""Relocation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OUseThPTvUeoOHU9revhojRpHO8DZeeW
"""

n,q = map(int,input().split())
final_ans = []
init_position = list(map(int,input().split()))
for i in range(q):
  a,b,c = map(int,input().split())
  if a==1:
    init_position[b-1] = c
  else:
    distance = abs(init_position[b-1] - init_position[c-1])
    final_ans.append(distance)
for ans in final_ans:
  print(ans)

