# -*- coding: utf-8 -*-
"""Rijeci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/155_mhKkVHiwMISxz6PL8b3nolHFsx9HF
"""

from sys import stdin,stdout
num = int(input())
count_a = 0
count_b = 1
for i in range(num-1):
  temp = count_a
  count_a = count_b
  count_b += temp
print(str(count_a)+ " "+str(count_b))

! python code.py < input.txt

