# -*- coding: utf-8 -*-
"""Roaming_numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iWLZNE8ctQny-5zc5CkXujn7hKVRthR9
"""

num = float(input())
print(round(num * 1000 * (5280/4854)))

from sys import stdin,stdout
num = float(stdin.readline())
ans = round(num * 1000 * (5280/4854))
stdout.write(str(ans))