# -*- coding: utf-8 -*-
"""Saving daylight.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16zVuq2jUdCaNawS2Z8TQYF-URbhiu983
"""

while(True):
  try:
    list_ = input().split()
    if len(list_)==0:
      break
    else:
      Month,date,year,mrng,night = list_
      rise,rise_min = map(int,mrng.split(":"))
      sunset,set_min = map(int,night.split(":"))
      hrs = sunset-rise
      min = set_min-rise_min
      if min <0:
        min = 60 + (min)
        hrs -= 1
      print(Month,date,year,hrs,"hours",min,"minutes")
  except EOFError:
    break

from sys import stdin,stdout
while(True):
    list_ = stdin.readline().split()
    if len(list_)==0:
      break
    else:
      Month,date,year,mrng,night = list_
      rise,rise_min = map(int,mrng.split(":"))
      sunset,set_min = map(int,night.split(":"))
      hrs = sunset-rise
      mins = set_min-rise_min
      if mins <0:
        mins = 60 + (mins)
        hrs -= 1
      stdout.write(Month + " ")
      stdout.write(date + " ")
      stdout.write( year + " ")
      stdout.write( str(hrs) + " ")
      stdout.write("hours ")
      stdout.write( str(mins) + " ")
      stdout.write( "minutes")
      stdout.write("\n")

