# -*- coding: utf-8 -*-
"""Saving_for_Retirement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Syjy_coy45elmZGXvutl9Cgh6kGyFey
"""

B,Br,Bs,A,As = map(int,input().split())
bob_earning = (Br - B) * Bs
i = 0
Alice_earn = 0
while (Alice_earn <= bob_earning ):
  Alice_earn += As
  i += 1
print(A + i)

