# -*- coding: utf-8 -*-
"""sevenWonders.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-u0hZAGDp96VKiy1pJ_7IBEyvec9P8vp
"""

seq = input()
t = seq.count("T")
c = seq.count("C")
g = seq.count("G")
count = sorted([t,c,g])
print(t*t+c*c+g*g+count[0]*7)

count

