# -*- coding: utf-8 -*-
"""Shooping list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2aqPbYijsGlBSynExXLRkXOwEeQk0CL
"""

n,item = map(int,input().split())
common = []
first_list = input().split()
dic = {}
for item in first_list:
  dic[item] = 1
for i in range(n-1):
  new_item = input().split()
  for item in new_item:
    if item in dic:
      dic[item] += 1
for keys,values in dic.items():
  if values == n:
    common.append(keys)
common = sorted(set(common))
print(len(common))
for c in common:
  print(c)

22