# -*- coding: utf-8 -*-
"""Skocimis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10oAIiRiFgshizz5QIN6x3lyz_MSmv1m1
"""

a,b,c = map(int,input().split())
a_sub_b = b-a-1
c_sub_b = c - b -1
print(max(a_sub_b,c_sub_b))