# -*- coding: utf-8 -*-
"""some_sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5e6jw5Zg7JmLoM_9ARvXWwAM-Oruurq
"""

from sys import stdin,stdout
num = stdin.readline()
n1 = 2
n2 = 3
num = int(num)
for i in range(1,num):
  n1 += 2 + i
  n2 += 3 + i

if (n1+n2)%2 ==0:
  if n1%2 == 0 and n2 % 2 ==0:
    stdout.write("Even")
  else:
    stdout.write("Odd")
else:
  stdout.write("Either")

