# -*- coding: utf-8 -*-
"""sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11lOfbb49B4eJjXVNfl9dVBa6GFUpbofn
"""

while True:
  try:
    val_dict = {}
    num = int(input())
    if int(num) ==0:
      break
    else:
      for i in range(num):
        last_names = input()
        string_ = last_names[0]+last_names[1]
        if string_ in val_dict:
          val_dict[string_].append(last_names)
        else:
          val_dict[string_] = [last_names]
    for i in sorted(val_dict.keys()):
      for j in range(len(val_dict[i])):
        print(val_dict[i][j])
    print("\n")
  except EOFError:
    break