# -*- coding: utf-8 -*-
"""Soylent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LOSoeZZJlQ0PIHhphUorwvaaa3MpVn5X
"""

from math import ceil
n = int(input())
for i in range(n):
  calories = int(input())
  print(ceil(calories/400.0))