# -*- coding: utf-8 -*-
"""Stand on Zanzibar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xK2sa0wssQdKopJVGm42RLrgQ7uh0c3x
"""

num = int(input())
for i in range(num):
  number = list(map(int,input().split()))
  init = number[0]
  outside = 0
  for i in range(0,len(number)-2):
    new_num = number[i+1]
    diff = new_num - 2* init
    if diff > 0 :
      outside += diff
    init = new_num
  print(outside)

