# -*- coding: utf-8 -*-
"""Stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/184AiQEUJzsAHyYRY9_jPhDRPRW_s5A-P
"""



input_list =[]
while True:
  try:
    list_1 = list(map(int,input().split()))
    if len(list_1) ==0:
      break
  except EOFError:
    break
  if(len(list_1)) >1:      
    list_1.pop(0)
    input_list.append(list_1)
if (len(input_list)>0):
  for i in range(len(input_list)):
    max_ = max(input_list[i])
    min_ = min(input_list[i])
    range_ = max_ - min_
    print('{} {}{} {} {} {}'.format("case",i+1,":",min_,max_,range_))

import sys 
  
  
for line in sys.stdin: 
    if 'q' == line.rstrip(): 
        break
    print(f'Input : {line}') 
  
print("Exit")

import sys
lines = sys.stdin.readlines()
print (lines)

