# -*- coding: utf-8 -*-
"""Sum_square_error.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1gdnXhEMo1ecnBKSL2vS1SXKCDoV-6P
"""

num = int(input())
for i in range(num):
  k,b,n = map(int,input().split())
  total_sum = 0
  while(n>0):
    tmp = n%b
    total_sum += int(tmp) ** 2
    n = n/b
  print(k,total_sum)