# -*- coding: utf-8 -*-
"""SumKindOfProblem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mBIGjIeQ4iUjhLjmVoqvBk1QwKnW5W1H
"""

num = int(input())
for i in range(num):
  a,b = map(int,input().split())
  sum_N = int(b*(b+1)/2) 
  sum_odd = int(b*b)
  sum_even = int(b*(b+1))
  print(a,sum_N,sum_odd,sum_even)

1