# -*- coding: utf-8 -*-
"""Symmetric_order.ipyb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-BreTkc8GjL1uQqoMVEim5G19AJh_lz3
"""

itr = 0
while(True):
  n = int(input())
  if (n ==0):
    break
  else:
    itr += 1
    first_name = []
    last_name = []
    for i in range(1,n+1):
      name = input()
      if i%2 != 0:
        first_name.append(name)
      else:
        last_name.insert(0,name)
    print("SET",itr)
    for j in range(len(first_name)):
      print(first_name[j])
    for k in range(len(last_name)):
      print(last_name[k])

