# -*- coding: utf-8 -*-
"""the_last_problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Np9jBixnjuaBg3B16q00VM-0yXqGTdm
"""

name = input()
print("Thank you, {}{} and farewell!".format(name,','))