# -*- coding: utf-8 -*-
"""Tower Constructions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uAaMlhurTOsijLUh4QxfDhyOqZIfV1rm
"""

n = input()
values  = list(map(int,input().split()))
tower = 1
curr = values[0]
for i in range(1,len(values)):
  if values[i]>curr:
    tower +=1
  curr = values[i]
print(tower)