# -*- coding: utf-8 -*-
"""Yin_and_Yang_stones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16-6WHXsH6xLds3j3byVjiZgI8jaPgQsY
"""

input_ = input()
while(True):
  if "WWB" in input_:
    input_ = input_.replace("WWB","W")
  elif "WBW" in input_:
    input_ = input_.replace("WBW","W")
  elif "BWW" in input_:
    input_ = input_.replace("BWW","W")
  elif "WBB" in input_:
    input_ = input_.replace("WBB","B")
  elif "BBW" in input_:
    input_ = input_.replace("BBW","B")
  elif "BWB" in input_:
    input_ = input_.replace("BWB","B")
  else:
    break
if input_ =="WB" or input_ =="BW":
  print(1)
else:
  print(0)