# -*- coding: utf-8 -*-
"""Zamka.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iWqVtahzkV0Juq3RtkCWlje57q0DKR0Y
"""

l = int(input())
d = int(input())
x = int(input())
ans = []
for i in range(l,d+1):
  j = str(i)
  sum = 0
  for k in range(len(j)):
    sum += int(j[k])
  if sum == x:
    ans.append(int(j))
print(ans[0])
print(ans[-1])